### ISSUE TITLE
关于参照传承字形的一些建议

### ISSUE THREAD

**Issue by HoTszHo** [lxgw/LxgwWenkaiTC#11]
首先非常感谢您补全字体，我非常喜欢。
个人感觉这种类型的字体不是很适合全盘照搬传承字形，不是宋体的话总感觉有点奇怪。
提个小意见，可以把良字的首笔（短横）换成像言字首笔那样的横点吗？
还有就是尚和尚字头的字不是很统一

**Comment by lxgw** [comment]
对于「尚」部件和尚字头「𫩠」，一点字坊的检校表是这么规定的：

![image](https://user-images.githubusercontent.com/51902309/196370366-7bcf631b-5e86-4dda-b99b-02ce04ef234f.png)

**Comment by HoTszHo** [comment]
> 对于「尚」部件和尚字头「𫩠」，一点字坊的检校表是这么规定的：
> 
> ![image](https://user-images.githubusercontent.com/51902309/196370366-7bcf631b-5e86-4dda-b99b-02ce04ef234f.png)
> 
> 「尚」部件作偏旁的时候，美观上也可写作「反小」。
> 

明白您的考量了

**Comment by lxgw** [comment]
另外有关「良」部件，个人认为良部件的一横比下面的艮要长一些，不适用于短横变点的规则。当然，关于良部件的问题[已经有人向一点字坊方面提出了](https://github.com/ichitenfont/inheritedglyphs/issues/21)。
