### ISSUE TITLE
漢字以外的字元

### ISSUE THREAD

**Issue by SyaoranHinata** [lxgw/LxgwWenkaiTC#12]
半閉央圓唇元音ɵ應當是小楷o內有一橫的樣子
現在卻變成清齒擦音θ的樣子

**Comment by lxgw** [comment]
已記録，下个版本更新。

**Comment by SyaoranHinata** [comment]
感謝！辛苦了！！

**Comment by lxgw** [comment]
實在抱歉，0.931 更新並未修改該字形，下次更新將修正。

**Comment by lxgw** [comment]
實在抱歉，0.931 版本更新並未修正該字元，下次更新將修正。

**Comment by lxgw** [comment]
[v0.932 已修正。](https://github.com/lxgw/LxgwWenkaiTC/releases/tag/v0.932)
