### ISSUE TITLE
【置頂】增補漢字需求在此指出，不要另開議題。

### ISSUE THREAD

**Issue by lxgw** [lxgw/LxgwWenkaiTC#13]
如果您迫切需要本字型支援某個字，請在此指出，不要另開議題，以便於整理。

提交缺字前，請將本字型[更新到最新版本](https://github.com/lxgw/LxgwWenkaiTC/releases/latest)，並在本字型下嘗試輸入您需要的字。

如果您的加字需求被採納，提交的字也會加到[霞鶩文楷 SC 完整版](https://github.com/lxgw/LxgwWenKai)和 [Lite 版](https://github.com/lxgw/LxgwWenKai-Lite)。

**Comment by GrimPixel** [comment]
希望可以考慮古將棋中的字：𠵇、𩹄、䳲、𦬨。
https://ja.wikipedia.org/wiki/%E5%B0%86%E6%A3%8B%E9%A1%9E%E3%81%AE%E9%A7%92%E3%81%AE%E4%B8%80%E8%A6%A7

**Comment by LAONZENA** [comment]
缺少两个字:穩/隱

**Comment by lxgw** [comment]
> 缺少两个字:穩/隱

請截圖。

**Comment by LAONZENA** [comment]
![Uploading 截圖 2024-04-23 上午1.58.18.png…]()

**Comment by LAONZENA** [comment]
<img width="1148" alt="截圖 2024-04-23 上午1 58 18" src="https://github.com/lxgw/LxgwWenkaiTC/assets/167774315/b68f31dd-df5d-4855-a551-475072a28530">

**Comment by LAONZENA** [comment]
感谢🙏

**Comment by lxgw** [comment]
由於字體文件越發臃腫，v1.330 發佈後暫時關閉加字通道，不會接受用戶加字請求，敬請諒解。
