### ISSUE TITLE
有兩個部首反了

### ISSUE THREAD

**Issue by Ayaginu-Sue** [lxgw/LxgwWenkaiTC#17]
今天做 Astalia 的時候發現的問題，順便看了一下霞鶩文楷發現了不一樣但類似的問題。

TC 版本中的 ⺲U+2EB2 和 ⺳U+2EB3 反了。

![圖片](https://github.com/lxgw/LxgwWenkaiTC/assets/75211921/f9305525-5337-40ff-87f0-b90f5aeb2758)

從上到下是等線，霞鶩文楷 TC，霞鶩文楷。

**Comment by lxgw** [comment]
收到，下个版本修復。
