### ISSUE TITLE
字體有「慤」（U+6164），顯示成「𢡱」，卻缺收了「𢡱」（U+22871）本身

### ISSUE THREAD

**Issue by haydenwong7bm** [lxgw/LxgwWenkaiTC#19]

**Comment by lxgw** [comment]
這應該是疏漏原因，早前收錄了「稽」的分離字「𥠻 `U+U+2583B`」和「戋」的分離字「㦮 `U+39AE`」，但並沒有考慮「慤」在擴展 B 區也有分離字。後續版本會收錄這個字。
