### ISSUE TITLE
小小建議與期待

### ISSUE THREAD

**Issue by tonyhuan** [lxgw/LxgwWenkaiTC#2]
很喜歡Klee這款字型，謝謝孤鹜先森補全並把日文漢字寫法修正。
身為繁體中文使用者，標點符號沒有置中總覺得不習慣而無法全面使用，覺得可惜。
當注意到有這個版本時，很開心以為是針對繁體使用者修改，但發現是恢復Klee日文漢字寫法，稍微有點小小沮喪。
建議這個恢復舊字體的版本，取名為比較貼近實際的「日文漢字版」。
期待當您有空閒時，可以增加一個標點符號，、：；。？！上下左右置中的版本。
最近主字型改版很勤，符號全形及等寬字都很實用，感謝！

**Comment by lxgw** [comment]
本字型大部分字並不是恢復日文漢字寫法，而是改成了舊字形（又稱「傳承字形」）的寫法，以接近康熙字典的字形為準。如「飽」「選」等字，與日文漢字寫法有差別。

至於您所提到的「標點置中」，本人目前正在考慮。

**Comment by tonyhuan** [comment]
瞭解了，感謝您

lxgw ***@***.***> 於 2021年8月9日 週一 下午11:11寫道：

**Comment by SyaoranHinata** [comment]
傳承字形並不是日文字形，在港臺等繁體（正體）字地區裏，仍然天天在用，存活於日常生活中的周遭。

傳承字形更講究字理，遵從傳統文字學重要字書，與漢字字形的設計美學需求也更匹配，比各地敎育標準好。

**Comment by mega5241p** [comment]
我也很喜歡LxgwWenkai這字體
跟教科書體很像也很好看，很想要用在給小朋友學習上
不過TC版是對應傳承字形，希望作者有機會推出教育標準版
感恩！

**Comment by SyaoranHinata** [comment]
臺標字已經有But Ko在改，不必一窩蜂都改成臺標，浪費人力。
再者現在已有非常多的臺標字形字型，開源或付費的皆有，早有非常多選擇。
反而是傳承字形字型，如果要比較嚴格遵從字理、遵從《推薦字形表》的話，選擇是非常非常少。
多一款臺標字型，對臺標來說只是錦上添花；
多一款嚴格傳承字形，對傳承字形來說卻是荒漠甘泉。

我個人倒希望，現在的識字敎育可以撥亂返正，破開唯臺標是尚的鳥籠。
初小時可以先只依一套字形讓孩童學寫，
但要是他們自行學到其他也正確的字形，就不要打交叉，不要硬性強迫他們改正，
稍爲高階時，更應該讓他們學到不同的正確字形，
不管他們寫哪個，總之最少要知道這些字形皆正確，皆不是錯字，
這才不會讓像Zonble、董福興等IT界人士批鬥傳承字形的荒誕鬧劇重演又重演。

**Comment by siaoyi** [comment]
希望有個分支版本將一對一的簡化字編碼映射到傳統字上，這樣拿來作為屏幕顯示字型，可以將大部分簡化字顯示成傳統字。而一對多的簡化字則不映射，這樣就基本上不會發生顯示錯別字的情況。

**Comment by lxgw** [comment]
> 希望有個分支版本將一對一的簡化字編碼映射到傳統字上，這樣拿來作為屏幕顯示字型，可以將大部分簡化字顯示成傳統字。而一對多的簡化字則不映射，這樣就基本上不會發生顯示錯別字的情況。

想過做一款類似[「繁媛明朝」](https://github.com/ayaka14732/FanWunMing)那樣能夠處理簡轉繁的字體，但是不知道有沒有相應的工具……

**Comment by tonyhuan** [comment]
> > 希望有個分支版本將一對一的簡化字編碼映射到傳統字上，這樣拿來作為屏幕顯示字型，可以將大部分簡化字顯示成傳統字。而一對多的簡化字則不映射，這樣就基本上不會發生顯示錯別字的情況。
> 
> 想過做一款類似[「繁媛明朝」](https://github.com/ayaka14732/FanWunMing)那樣能夠處理一簡對多繁的字體，~但是不知道有沒有相應的製作工具……~
> 
> 在繁媛字體作者那裏找到了 [OpenCCFontGenerator](https://github.com/ayaka14732/OpenCCFontGenerator)，正在摸索……

去年諮詢時，該作者曾表示您的字體「[需要修改多處程式碼後可以生成字型檔](https://github.com/ayaka14732/OpenCCFontGenerator/issues/1#issuecomment-945443617)」，當時的成果測試後有效。👍

**Comment by GuiWonder** [comment]
> > 希望有個分支版本將一對一的簡化字編碼映射到傳統字上，這樣拿來作為屏幕顯示字型，可以將大部分簡化字顯示成傳統字。而一對多的簡化字則不映射，這樣就基本上不會發生顯示錯別字的情況。
> 
> 想過做一款類似[「繁媛明朝」](https://github.com/ayaka14732/FanWunMing)那樣能夠處理一簡對多繁的字體，~但是不知道有沒有相應的製作工具……~
> 
> 在繁媛字體作者那裏找到了 [OpenCCFontGenerator](https://github.com/ayaka14732/OpenCCFontGenerator)，正在摸索……

可以試一下這個 https://github.com/GuiWonder/TCFontCreator

**Comment by lxgw** [comment]
> > > 希望有個分支版本將一對一的簡化字編碼映射到傳統字上，這樣拿來作為屏幕顯示字型，可以將大部分簡化字顯示成傳統字。而一對多的簡化字則不映射，這樣就基本上不會發生顯示錯別字的情況。
> > 
> > 
> > 想過做一款類似[「繁媛明朝」](https://github.com/ayaka14732/FanWunMing)那樣能夠處理一簡對多繁的字體，~但是不知道有沒有相應的製作工具……~
> > 在繁媛字體作者那裏找到了 [OpenCCFontGenerator](https://github.com/ayaka14732/OpenCCFontGenerator)，正在摸索……
> 
> 可以試一下這個 https://github.com/GuiWonder/TCFontCreator

感谢推薦。不過轉換會提示 Syntax Error，不知道哪裏操作錯誤：
![image](https://user-images.githubusercontent.com/51902309/176125461-76a6477e-0ced-4d73-8a6c-9d32faf13cf7.png)

**Comment by GuiWonder** [comment]
> > > > 希望有個分支版本將一對一的簡化字編碼映射到傳統字上，這樣拿來作為屏幕顯示字型，可以將大部分簡化字顯示成傳統字。而一對多的簡化字則不映射，這樣就基本上不會發生顯示錯別字的情況。
> > > 
> > > 
> > > 想過做一款類似[「繁媛明朝」](https://github.com/ayaka14732/FanWunMing)那樣能夠處理一簡對多繁的字體，~但是不知道有沒有相應的製作工具……~
> > > 在繁媛字體作者那裏找到了 [OpenCCFontGenerator](https://github.com/ayaka14732/OpenCCFontGenerator)，正在摸索……
> > 
> > 
> > 可以試一下這個 https://github.com/GuiWonder/TCFontCreator
> 
> 感谢推薦。不過轉換會提示 Syntax Error，不知道哪裏操作錯誤：（已經在 appdata 文件中指定 FontForge 和 Python 的位置） ![image](https://user-images.githubusercontent.com/51902309/176125461-76a6477e-0ced-4d73-8a6c-9d32faf13cf7.png)

g)

使用完整版（TCFontCreator_full.7z）無需在 appdata 文件中指定 FontForge 和 Python 的位置，下載解包直接用。我剛才測試了一下，沒有報錯，可能是你的python版本問題。軟件提供兩個内核，一個不行就換另一個試試。

**Comment by GuiWonder** [comment]
> > > > 希望有個分支版本將一對一的簡化字編碼映射到傳統字上，這樣拿來作為屏幕顯示字型，可以將大部分簡化字顯示成傳統字。而一對多的簡化字則不映射，這樣就基本上不會發生顯示錯別字的情況。
> > > 
> > > 
> > > 想過做一款類似[「繁媛明朝」](https://github.com/ayaka14732/FanWunMing)那樣能夠處理一簡對多繁的字體，~但是不知道有沒有相應的製作工具……~
> > > 在繁媛字體作者那裏找到了 [OpenCCFontGenerator](https://github.com/ayaka14732/OpenCCFontGenerator)，正在摸索……
> > 
> > 
> > 可以試一下這個 https://github.com/GuiWonder/TCFontCreator
> 
> 感谢推薦。不過轉換會提示 Syntax Error，不知道哪裏操作錯誤：（已經在 appdata 文件中指定 FontForge 和 Python 的位置） ![image](https://user-images.githubusercontent.com/51902309/176125461-76a6477e-0ced-4d73-8a6c-9d32faf13cf7.png)

使用完整版（TCFontCreator_full.7z）無需在 appdata 文件中指定 FontForge 和 Python 的位置，下載解包直接用。我剛才測試了一下，沒有報錯，可能是你的python版本問題。軟件提供兩個内核，一個不行就換另一個試試。

**Comment by lxgw** [comment]
> 建議使用完整版（TCFontCreator_full.7z）無需在 appdata 文件中指定 FontForge 和 Python 的位置，下載解包直接用。我剛才測試了一下，沒有報錯，可能是你的python版本問題。軟件提供兩個内核，一個不行就換另一個試試。

感谢作者，已经成功了，是我一开始下错版本了。

**Comment by siaoyi** [comment]
曾用過一段時間的繁媛明體，智能處理一簡對多繁也經常對錯了。
樓上仁兄成功後可否分享一下成果呢？

**Comment by tonyhuan** [comment]
> 曾用過一段時間的繁媛明體，智能處理一簡對多繁也經常對錯了。 樓上仁兄成功後可否分享一下成果呢？

在下引用版主的作品，跟[GuiWonder](https://github.com/GuiWonder)的工具，整理了一款[原俠正楷](https://github.com/tonyhuan/GuanKiapTsingKhai)，做出來有幾個錯誤與限制，但大致還算堪用。
