### ISSUE TITLE
霞鹜文楷繁体版中“旋”字有误，如果也能顺带调整一下“夠”字的大小，那就锦上添花了

### ISSUE THREAD

**Issue by NoCommentsElder** [lxgw/LxgwWenkaiTC#5]
![3DCD1759-685C-402B-81F0-AC05B2107524](https://user-images.githubusercontent.com/91309393/134629867-1e43076e-8113-4fe8-b3fe-44ee8d3fb51c.jpeg)

**Comment by lxgw** [comment]
0.110 已更新。
