### ISSUE TITLE
有必要完全遵循《傳承字形部件檢校表》嗎？

### ISSUE THREAD

**Issue by lxgw** [lxgw/LxgwWenkaiTC#7]
一點字坊的[《傳承字形部件檢校表》](https://github.com/ichitenfont/inheritedglyphs)（下稱《檢校表》）將很多同質化的部件在字源上做了區分。但看了一下市面上很多非臺標的繁體中文字型，很多部件都與檢校表的不同，尤其是「辛」「旁」「良」之類的一般印刷字型首筆爲直點，而檢校表首筆爲橫的部件。此外，這些部件涉及的漢字較多，如一次性全部改完，需要更多的時間和精力。

0.112 版本中所帶的「音」「龍」「意」等首筆爲橫的字爲 Klee One 內建的隱藏字形，而其餘含此類部件的大多字，部件首筆都是直點。此外，檢校表中還有跟本字型及市面上很多繁體中文印刷字型不同的部件。而[「源音黑體」](https://github.com/MoneMizuno/Genne-Gothic)雖然有些部件遵循了傳承字形，但仍有部件與檢校表不同。

至於利用 [zi2zi](https://github.com/EuphoriaYan/zi2zi-pytorch) 進行 AI 造字，機器學習過程中會佔用大量的 GPU 資源，且推導出的圖片導入到字形製作軟件裏，輪廓上會有瑕疵。

因此，利用 issue 徵求大家的意見，是花費大量的業餘時間和精力去把所有部件轉化爲符合檢校表標準的字形，還是改成主流的字形，還是維持現狀，歡迎在此提出您的意見。

當然，如果想要質疑我對待這款字型的態度不夠端正，或者對正體中文用戶或傳承字形愛好者不夠負責，等等，也請直說，不必轉彎抹角，本人虛心接受。

**Comment by Zonz-Ly** [comment]
其實是沒有必要的～
在下作爲一點字坊的成員，且也參與了一點點《檢校表》編撰工作，可以給出一些參考信息：

1. 《檢校表》是一個傳承字形推薦表，而非強制標準。我們提前做好了不同字源的字形的區分工作，同時考慮了實用度和美觀度，力求在字源和美觀之間做到最大限度的平衡；這樣，字體設計師可以直接拿起來就用，避免很多對字形的糾結和麻煩。
2. 既然是一個**推薦**表，那麼當然也可以不按推薦來設計字形。如果不按照我們的推薦來設計字形，我們仍提醒字體設計師在設計字形時要關注字形之美，比如豎點、斷筆等；儘量遠離〝臺敎標〞、〝港標〞畸形標準，這兩個標準都進了「手寫筆形強加於印刷字體」的誤區。
3. 我們仍推薦儘可能參考《檢校表》來設計字形，並不是說符合《檢校表》的才能是傳承字形，而是說《檢校表》是我們團隊全員經過認真思考和總結、仔細求證和斟酌後，給出的關於傳承字形的最優解。
4. 「辛」「旁」「良」之類的字的字形，如首筆均改作橫，工作量不是一般的巨大，我認為設計師可以量力而行；如果沒有充足的精力，直接作豎點也是可以理解的。且作豎點的字形在古籍上也並非少數。

**Comment by SyaoranHinata** [comment]
這麼說，如果說是否「必須」，我們不是任何權勢力量，沒有「必須」這回事。但如果有沒有「必要」，以在下這種喜愛中文字形的人來說，非常極度有必要。

市面上的非臺標的繁體中文字型，爲什麼不少會跟檢校表有不同？就是因爲製作的朋友並沒有從漢字文字學角度出發。即使不依臺標，但取形上也沒有認眞的考慮字理。

就像你說，不少非臺標字形的「辛部件」、「音部件」等用豎點。有什麼問題呢？字理上，「辛」的上方不是「立」。能不與「立」混同的話，就不應該混同。「辛」的首筆作短橫（楷體的話可以作側點，但不要作豎點，這點在《筆畫表》裏已詳述），有字理、學術依據，在漢字設計的美學要求上也不相悖，那麼，個人就不希望做差不多先生。

良好的傳統值得繼承並傳延下去，差不多先生的習慣則適宜改進。竊以爲做人做事各方面都是如此，才能精益求精。

因此，我完全沒有任何力量，去令誰「必須」都依照這個推薦標準。但我非常強烈且極度熱切地期望，能有完全依從這標準的字形，而且越多越好。

**Comment by dine2014** [comment]
樓上的帖子隱含着這樣一種邏輯：遵從 etymological principle，就是出於理性考量，不遵從 etymological principle，就是考慮不周全，亦或者個人品質有問題（「差不多先生」）。至於其他的字形上的訴求（通用程度、Pan-CJK），這些訴求和 etymological principle 如何取捨，都不重要，只知道他們「並沒有從漢字文字學角度出發」就夠了。

**Comment by SyaoranHinata** [comment]
請樓上不要妄自猜度，不然就只是打稻草人，甚或予人扣帽子之不良感觀。

現在這裏的前提，是需要有一款儘可能遵循《檢校表》的字型，在這前提下解釋爲甚麼有此需要。我並沒有反對也有其他以通用程度爲最優先考慮、以支援Pan-CJK爲最優先考慮的字型可以選擇，也沒有說這些方面就是「考慮不周全」或「品質有問題」。只要它們不是強迫我使用即可。

反而在現實裏的問題是，是不是每一次的字型製作，都必須要以通用程度、Pan-CJK等考慮，去壓倒字理字源的考慮，以致市面上盡力遵從字理字源的字型如此匱乏？難道在漢字字型上，漢字文字學角度反而是no stake嗎？這事情不本末倒置、不很荒謬嗎？

此外，自問《檢校表》已充份考慮各方因素和需求，絕不與漢字字型所需美學、通用程度等考慮相衝突。

**Comment by dine2014** [comment]
4樓刪了，但刪後5樓的「樓上」對不上，容易讓人誤以爲是指1樓或2樓。我當初評論是反對把非字源字理派説成「差不多先生」，將不符合和沒有考慮劃等號等等，但方式有誤。

**Comment by aikahiiragi** [comment]
不好意思我遲來，我是希望在世界上會有多一些完全符合《檢校表》的字型可以使用，我不怕要等久一些，但我怕出來的字型是半桶水，違反《檢校表》的規定。因為在世界上，違反《檢校表》的規定太多了，遵從《檢校表》的字型卻少得很，大廠商要麼只盲目追髓邪惡的台標，要麼就無標準主義，不放字理字源在眼內，令漢字的字理字源在字型界裏幾乎完全被忽視。

這款字體是手寫或楷體風的，其實除了《檢校表》，更應同時參考《筆畫表》，因為《筆畫表》當中有很多規定，讓手寫字形不必盲目依從印刷字形。例如「辛」「旁」「音」「龍」「意」等等的「辛字頭」可以用點，只要點與長橫分離便可以，不用變成兩橫，這會比較自然，同時也可以與「立字頭」區分（「立字頭」用直點，直點末部與橫相連）。

**Comment by lxgw** [comment]
感謝大家的討論與建議，本 issue 將關閉。
