### ISSUE TITLE
v1.200未來計劃?

### ISSUE THREAD

**Issue by Marcus98T** [lxgw/LxgwWenkaiTC#8]
> ~~另，本字体也有供繁体中文用户和旧字形爱好者使用的 [繁体中文版](https://github.com/lxgw/LxgwWenkaiTC)，基于轻便版制作，采用旧字形写法，主要采用 Klee One 的隐藏字形，部分部件手动修改，处于半弃更状态。~~ 目前已有基于 Klee One 改造的繁体中文字体 [芫荽 / Iansui](https://github.com/ButTaiwan/iansui)，采用台湾地区的「国字标准字形」，有繁体中文排版需求的可使用「芫荽」字体。自 v1.200 版本起，会从「芫荽」字体中选出改得比本字体更好的字形替换本字体原有的字形。

我不想引起誤會，不過我感覺[本字體還沒有修完](https://github.com/lxgw/LxgwWenkaiTC/issues/3)、您想要放棄了它嗎？我覺得我們需要有選擇，而不是被迫使用台灣標準字形。所以我建議你放棄之前完成這個字體。謝謝。

**Comment by lxgw** [comment]
E-mail 已答覆。簡體版基本上沒有甚麼大問題要改的了，繁體版日後會繼續調整，不過可能需要更長的時間。
